[DATA]
dataset_url = "http://download.tensorflow.org/data/speech_commands_v0.01.tar.gz"
download_dir = "../data"
augmented = true
subset_labels = [
  "yes",
  "no",
  "stop",
  "go",
  "on",
  "off",
]

[LEARNING]
epoch = 100
batch = 64
val_ratio = 20.0
test_ratio = 10.0
